language: node_js

before_install:
- rvm install 2.3.1

notifications: # set notification options
  email: false

sudo: false

node_js:
  - "7"

env:
  - CXX=g++-4.8

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
services:
  - postgresql

script:
  - "bin/test"
