default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: studious_development

test:
  <<: *default
  database: studious_test

production:
  <<: *default
  database: studious
