# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f00f1b2f006cc3aa1e5ac9fc5d06e5edbd2603e9ef8882402ed227decc5d25a6303c631eb61ad36bb49800897dbe011a74fb8495237447e9be5367321a8762c8

test:
  secret_key_base: 790c64d2315ca0f7c218ae0c14bd6dbb4ee5251f2d685395457059b2f8738748c3d610f221e280cbdecad5b5fd63bfbee9ef825344f8ee60e8891c787af9c7f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
